### ISSUE TITLE
a few typos

### ISSUE THREAD

**Issue by musicmagix** [sayam93/Pi-Voice-Assistant#2]
This is my first Issue/Contribution here. Please be patient and understanding.

I found a few issues in this, otherwise very interesting, build:

Step 95:  The Instruction "Edit the ~~done.sh~~" [should be detected.sh according to command]
Step 98:  Wrong file edited?: sudo nano /home/username/wyoming-enhancements/~~done.sh~~ [should be monitor_done.sh according to instruction]
Step 100: Spelling mistake in the third filename: [should be disconnect instead of disonnect]

**Comment by musicmagix** [comment]
Can someone with more knowledge than me create a script which automatically replaces all the [username] fields with my actual username? It's tedious and (error prone) to manually change them in so many lines.

**Comment by sayam93** [comment]
> This is my first Issue/Contribution here. Please be patient and understanding.
> 
> I found a few issues in this, otherwise very interesting, build:
> 
> Step 95: The Instruction "Edit the ~done.sh~" [should be detected.sh according to command] Step 98: Wrong file edited?: sudo nano /home/username/wyoming-enhancements/~done.sh~ [should be monitor_done.sh according to instruction] Step 100: Spelling mistake in the third filename: [should be disconnect instead of disonnect]

Thanks for pointing these out. Fixed now.

**Comment by sayam93** [comment]
> Can someone with more knowledge than me create a script which automatically replaces all the [username] fields with my actual username? It's tedious and (error prone) to manually change them in so many lines.

@musicmagix You could fork and edit the readme.md file. Use find and replace to replace all the username fields with yours and save. When done, just delete the fork.

**Comment by musicmagix** [comment]
That‘s a good idea, thanks.

I was thinking of a more global solution. Is there no way to define once and use forever a variable [username]?
